/**
 * One-off helper: downloads the webfonts from Google and rewrites the CSS to
 * local paths. Run once, commit the result. The site itself never talks to Google.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { join, basename } from 'node:path';

const CSS_URL = 'https://fonts.googleapis.com/css2'
  + '?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,500'
  + '&family=Inter:wght@400;500;600&display=swap';

// Google serves woff2 only to browsers that claim to support it.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
  + 'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const OUT_DIR = 'assets/fonts';

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();
const urls = [...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2/g) ?? [])];
if (!urls.length) throw new Error('no font URLs found in the Google CSS');

await mkdir(OUT_DIR, { recursive: true });
let local = css;
for (const url of urls) {
  const name = basename(new URL(url).pathname);
  const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
  await writeFile(join(OUT_DIR, name), bytes);
  local = local.replaceAll(url, `/assets/fonts/${name}`);
}

await writeFile(
  'css/fonts.css',
  `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n${local}`,
  'utf8',
);
console.log(`downloaded ${urls.length} font files`);
